### ISSUE TITLE
No test coverage report generated

### ISSUE THREAD

**Issue by andrewmarklloyd** [SoftwareEngineeringDaily/software-engineering-daily-api#12]
#### Steps to reproduce
- run `npm run test:coverage`
- Only tested on macOS Sierra
#### Expected
- Coverage report is printed to terminal as shown below and coverage directory is populated with appropriate metrics
```
=============================== Coverage summary ===============================
Statements   : 68.03% ( 349/513 )
Branches     : 51.52% ( 102/198 )
Functions    : 52.21% ( 59/113 )
Lines        : 68.8% ( 333/484 )
================================================================================
```
#### Observed
- Terminal prints "No coverage information was collected, exit without writing coverage information"

#### Possible Fix
- Without too much testing, updating from istanbul@0.4.5 to istanbul@1.0.0-alpha.2 generates the coverage report. Not sure if there are other ways to fix this with a different configuration.

**Comment by TheHollidayInn** [comment]
I'm fine with updating the library to fix!
