### ISSUE TITLE
Unfavoriting/unbookmarking doesn't work on dev servers

### ISSUE THREAD

**Issue by justinctlam** [SoftwareEngineeringDaily/software-engineering-daily-api#121]
Doesn't seem like unfavoriting/unbookmarking is working correct on the dev servers, but is ok on prod servers. Can someone double check? @jasonify @joshmorel

**Comment by jasonify** [comment]
@joshmorel  so the new changes are on staging/dev server so I am wondering if it could be related to the latest changes to the bookmark API

**Comment by joshmorel** [comment]
I will check tonight. I didnt touch existing favorite routes which may be the issue. @justinclam what route are you using?

**Comment by justinctlam** [comment]
https://sedaily-backend-staging.herokuapp.com/api/docs/#/favorite/post_posts__postId__unfavorite

**Comment by joshmorel** [comment]
What specific error are you getting? I've tested `develop` locally and also manually run some requests against staging with no issues.

FYI - here is a postman collection I created for SED, as well as a staging environment if you use postman:

https://gist.github.com/joshmorel/ab861866ccb478a449ce2936d7445533

**Comment by justinctlam** [comment]
I don't get an error when calling the API but when I query for bookmarks using /users/me/bookmarked, I still see the post even though I unfavorited it.

**Comment by joshmorel** [comment]
Oh I see. It all makes sense now. I even wrote a test for this case but the test wasn't properly written. :man_facepalming: 

Opening PR.

**Comment by jasonify** [comment]
PR Should be merged and on staging, @justinctlam  :)

**Comment by justinctlam** [comment]
Looks good guys! Thanks!
