### ISSUE TITLE
Create a label system for Issues/PR management

### ISSUE THREAD

**Issue by TheHollidayInn** [SoftwareEngineeringDaily/software-engineering-daily-api#14]
Open to discussion. Here are some ideas.

1. Help Wanted
2. Investigating 
3. In Progress
4. Ready for Review

**Comment by andrewmarklloyd** [comment]
Some suggestions:
- "Has Dependent PR"
- Not a label, but prefixing with "[WIP]" to indicate Work in Progress prevents merging, which would eliminate "In Progress"
- "Reviewed"

**Comment by Tofuus** [comment]
- `Critical`
- `Bite size` Easy bugs for people starting out
-  `Verified` Bugs that have confirmed and reproducible
- `Duplicate`

Different status labels

- Status: Blocked 
- Status: In Progress 
- Status: On Hold 
- Status: Review Needed


Different types

- Type: Question
- Type: Proposal
- Type: Documentation

**Comment by TheHollidayInn** [comment]
Created some. I'll keep it simple for now.
