### ISSUE TITLE
Recommended podcasts API endpoint might be broken

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/software-engineering-daily-api#152]
Either that or the clients are all not working.

**Comment by jasonify** [comment]
Was a frontend issue.

**Comment by crablar** [comment]
@jasonify I think something strange is still happening. On iOS, the "Most Viewed" list is identical to Recommendations

**Comment by jasonify** [comment]
Strange, it's different for me :/

**Comment by crablar** [comment]
Oh I am logged out, fixed
