### ISSUE TITLE
user/{userId} include ownUser boolean

### ISSUE THREAD

**Issue by joshmorel** [SoftwareEngineeringDaily/software-engineering-daily-api#156]
Working on the front-end to add public profile for any user. I'd like to conditionally display an "Edit Profile" link if it's the authenticated user's own user being viewed.

Given the current front-end, I'd need to make a call to `user/{userId}` and `user/me` which is not a huge issue, but an unnecessary api call.

There are two alternative options here as far as I can tell: 

* Change front-end to fetch "me" profile as soon as logging on
* Include an `ownUser` boolean to GET `user/{userId}` to back-end

Further alternate ideas are welcome. This might be a good first issue if agreed to.

**Comment by joshmorel** [comment]
After doing some work on the jobs board - I've identified that a more versatile option would be to just return the user's own id with the login call. Right now only the token is returned.

This way on whichever front-end and for whatever feature you can just use that id to compare vs the userId of any data object (job, comment, profile, etc) to affect the view.

@dfcook any thoughts?

**Comment by joshmorel** [comment]
Edited:  While working on the job MVP, I'll try to figure out if this is necessary or not. But thoughts on best practices for this scenario wouldn't hurt!

**Comment by dfcook** [comment]
I think the profile should be loaded at point of authentication and stored in the vuex store. It can be triggered in the app created event if the token is already in localStorage.

**Comment by joshmorel** [comment]
Good point. We just need to tweak when `fetchProfile` is called and me is set on the front-end. Currently, while doing manual testing the previous user is the vuex store if I don't re-fetch me. An edge case for real world scenarios , but still not a good thing! I'll close this issue and open a new issue on the front-end.
