### ISSUE TITLE
We shouldn't allow usernames with blank spaces?

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/software-engineering-daily-api#159]
Might be convinced to allow them in between but right now we have a few users with usernames that have spaces at the end / start which I am assuming were mistakes when inputting them (6 people).

Example of usernames  with spaces in between, we have a few (6) like this:
Some User
Jeff Butter

**Comment by crablar** [comment]
We could replace old users with blank spaces with underscores and disallow it going forward.
