### ISSUE TITLE
Issue: TravisCI not configured properly

### ISSUE THREAD

**Issue by edgar971** [SoftwareEngineeringDaily/software-engineering-daily-api#17]
TravisCI is linked correctly but the config seems to be incorrect.

**Comment by joshmorel** [comment]
I've confirmed locally that node 4.8 will not work with the current code base, and do we even care about it? So I would say vote for removing that from the version list when you get the config set up.

**Comment by TheHollidayInn** [comment]
I’m fine to use the latest stable version. I think that is 5.4?

**Comment by joshmorel** [comment]
Isn't 6.11 the latest with stable LTS version with 8.? soon to be LTC? 

Reference: https://github.com/nodejs/Release

**Comment by TheHollidayInn** [comment]
Ah, I was thinking npm not node.
