### ISSUE TITLE
Deleted comments should return empty content property or an alternate msg

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/software-engineering-daily-api#174]
Right now the client has to handle this but it should be the server to handle this. If a comment is marked as deleted, it should still return with other comments but it should not include the content field. Maybe include: 'This comment was deleted' or simply 'Deleted'. 

We are not actually deleting comments just in case we ever need to reference them later.

**Comment by abdulbasitkay** [comment]
Is anybody working in this? I'd like to.
To clarify, the returned body for a deleted comment would be something like this:
`{
  "result": {
    "_id": "507f1f77bcf86cd799439010",
    "__v": 0,
    "content": "Deleted",
    "dateCreated": "2017-10-30T01:05:39.674Z",
    "author": "507f1f77bcf86cd799439010",
    "post": "507f1f77bcf86cd799439010",
    "deleteed": true
  }
}`

**Comment by jasonify** [comment]
Nobody else is working on it :) & yeah thats right, let me know if you have any more questions.

**Comment by jasonify** [comment]
A nice to have (should be another issue) is to add the timestamp of deletion. I think the same applies to last edited. Should be part of the model I think.

```

{
....
"content": "Deleted on Dec 30 2018 at 3:30pm",
"deletedDate": "2018-12-30T01:05:39.674Z",
"datedLastEdited":  null  // maybe allow null or use wasEdited:bool? 
}
```

**Comment by abdulbasitkay** [comment]
They're really good suggestions and I thinks they should be different issues. I can do the timestamp thing but a bit cautious of have scope creep on this issue.
