### ISSUE TITLE
related-link 500 error when not authenticated

### ISSUE THREAD

**Issue by joshmorel** [SoftwareEngineeringDaily/software-engineering-daily-api#177]
There is a new error in develop branch when not authenticated. 

I'm pretty sure it's caused by switching to `votes.forEach` in the `relatedLink.model.js` `RelatedLinkSchema.statics.list` function in commit 8e69d003dc3ec6dbb893a8e1f01bd4e2aa5287cf

Here is the truncated error:

```json
{
    "message": "Internal Server Error",
    "stack": "Error: Cannot read property 'forEach' of undefined\n    at APIError.ExtendableError..."
}
```

**Comment by joshmorel** [comment]
I see now it is master and production

**Comment by jasonify** [comment]
Sorry what do you mean by master and production?

**Comment by joshmorel** [comment]
When I first noticed it, it was only in the develop branch. Now it is in the master branch and deployed production app (softwaredaily.com)

See below - if you are not logged in:

1) the related links are not displayed
2) the XHR returns a 500 error response

![related-links-issue](https://user-images.githubusercontent.com/10546720/37614567-71a54f76-2b81-11e8-8403-c6719fc65309.png)

**Comment by jasonify** [comment]
I see what you are saying now thanks. So sounds like it was a regression introduced in the last push.
