### ISSUE TITLE
Add the timestamp of deletion   (for comments + threads)

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/software-engineering-daily-api#189]
Add the timestamp of deletion.. Should be part of the model I think.
Querying a thread should not return it's contents (currently does if you have the id).

```

{
....
"content": "Deleted on Dec 30 2018 at 3:30pm", // This is put here by the comment.controller on the fly.
"deletionDate": "2018-12-30T01:05:39.674Z",
}
```

**Comment by abdulbasitkay** [comment]
check pull request #187, it adds deletion timestamp for comments
