### ISSUE TITLE
Setup Facebook app

### ISSUE THREAD

**Issue by andrewmarklloyd** [SoftwareEngineeringDaily/software-engineering-daily-api#20]
In order to fully implement #3 (adding social auth), there needs to be a Facebook app created and configured at https://developers.facebook.com

**Comment by TheHollidayInn** [comment]
To do this, you should just create your own dev account to use for testing, then add the example env vars to the .env.example file. I'll configure the real variables during deploy.

**Comment by andrewmarklloyd** [comment]
Ok that sounds good.
