### ISSUE TITLE
I'm seeing a failed JWT token issue from Travis a few times now

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/software-engineering-daily-api#203]
Any ideas? @andrewmarklloyd  or @joshmorel  ? 
<img width="1114" alt="screen shot 2018-04-11 at 5 01 28 pm" src="https://user-images.githubusercontent.com/150265/38649181-133bce0c-3daa-11e8-84d5-0ca1a408e8c2.png">

**Comment by jasonify** [comment]
Restarting it by hand fixes it but seems weird.

**Comment by andrewmarklloyd** [comment]
Might be a timeout issue. Do you have a full build trace?

**Comment by andrewmarklloyd** [comment]
Actually I think this is it https://travis-ci.org/SoftwareEngineeringDaily/software-engineering-daily-api/builds/364848062
