### ISSUE TITLE
Speed [enhancement]

### ISSUE THREAD

**Issue by SupremeRumHam** [SoftwareEngineeringDaily/software-engineering-daily-api#21]
Hey everyone,

This probably was discussed on the Slack channel and I just missed it but would love to have the option to pick a different speed for the audio.

**Comment by edgar971** [comment]
I believe this is part of the iOS or Android app, not the API itself.

**Comment by SupremeRumHam** [comment]
Oh sorry, I didn't notice. Still new to programming and Github. Thanks for being nice about it!!

**Comment by TheHollidayInn** [comment]
Hey @SupremeRumHam!  Thanks for posting :D 

@edgar971 is correct. This is something we would need to add to the apps. @themisterholliday has added it to an upcoming iOS release.

Here is the request on Android: https://github.com/SoftwareEngineeringDaily/SEDaily-Android/issues/6. I or someone else will be getting that handled soon!

**Comment by SupremeRumHam** [comment]
Awesome!! Glad to hear it!! If I think of anything else i'll add it, to the right Repo next time too!!

**Comment by TheHollidayInn** [comment]
Sound great! Closing then.
