### ISSUE TITLE
Listener Data Management

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/software-engineering-daily-api#221]
We need an API for getting a user's listened history. I'm not sure where the listen data is stored (InfluxDB, Firebase?) but it is definitely not easily accessible.

Once we have that API, it will be much easier to build:
- a custom recommendation system (we should probably replace our Raccoon powered one eventually)
- the ability to serve related links to people
- other collaborative filtering related features (connecting users who listen to similar material)

Opening up a discussion for how to tackle this problem.

**Comment by andrewmarklloyd** [comment]
I believe the user's listening history is stored in Mongo via the API, right @TheHollidayInn?
