### ISSUE TITLE
Add better error reporting to event stream

### ISSUE THREAD

**Issue by andrewmarklloyd** [SoftwareEngineeringDaily/software-engineering-daily-api#225]
@tyler-furby @abdulbasitkay @jasonify @joshmorel  I'm looking into better error reporting for the API. Currently it's up to each controller (or any class) to use the `sendError` helper. Here's an [example usage](https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/blob/develop/server/controllers/auth.controller.js#L229). What if instead we abstracted it to the [APIError.js](https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/blob/develop/server/helpers/APIError.js) class itself? So instead of every time a class creates the APIError and has to also use the `sendError` helper, what if the APIError just sent the error to the event stream instead?

**Comment by andrewmarklloyd** [comment]
#226 fixes an issue with the event stream API. It should be merged before we can make changes concerning this issue

**Comment by abdulbasitkay** [comment]
@andrewmarklloyd What you're proposing would be a better way to report an error but did you notice that not all `APIError` are reported to the event stream. We could either just stream every error or have way to specify which APIError is.

**Comment by andrewmarklloyd** [comment]
@abdulbasitkay I did see that. It’s only being sent in two classes right now. I was thinking if we just stream the error in APIError itself then people would not need to stream it in each class

**Comment by abdulbasitkay** [comment]
@andrewmarklloyd Okay that makes sense. If there isn't any drawback to streaming every error then I think we could go ahead with that.
