### ISSUE TITLE
Better and more consistent approach to env config

### ISSUE THREAD

**Issue by joshmorel** [SoftwareEngineeringDaily/software-engineering-daily-api#238]
As referenced in #231  - there are too many items in `/config/config.js` that are required `env` variables but only really relevant to production, (maybe) staging, and for specific devs working on those features. These are those related to external services - Stripe, Mail Chimp, etc.  They're not relevant to CI and for most devs doing core app work. 

I also noticed when starting to look at this that we are not fully consistent in how we many env variables. For example, `MAILCHIMP_KEY` is defined and accessed via `/config/config.js` while `STRIPE_PUBLIC_KEY` is accessed via `process.env` - so there may be an opportunity to be a bit more consistent.

Before putting in a PR - was  looking for some input on best option to organize from @jasonify  and @andrewmarklloyd. @abdulbasitkay  - your input would also be appreciated and I'm pretty sure this is  relevant to the work related to Cloud9 you're starting to look into. 

1) Define everything through `/config/config.js`. Make external service variables optional (`MAILCHIMP_KEY`, etc). 
2) Strip down `/config/config.js` to only those items that are core to the app, for external services use  `process.env` (what we are already doing with Stripe and AWS)

My preference is option 1 as it would be more explicit and overall more consistent but I'm open to either. For option 1 in `Joi` we can make the optional items simple `optional()` or use a fake key default like `default('mailchimp_key-us6')`. I think the later would be best.

I'm also not sure why we have a separate `.env.docker_example`. I think this and `.env.local_example` can be removed and we can just use a `.env.example`.

**Comment by jasonify** [comment]
Ahh yeah we need to be a bit more consistent. 

I think keeping the config.js would get my upvote.
Can we just leave the defaults inside the .env.example?

This would let everyone quickly see everything that is being used and it would also mean it can throw a nice error / warning  in production in case those keys are ever missing.

**Comment by andrewmarklloyd** [comment]
I agree with @jasonify it would help with debugging in production and cause the least amount of changes. 

It’s a good call yo centralize the other services variables in the config.js too

**Comment by joshmorel** [comment]
Yep what your saying makes sense.

I would suggest then - to address the original issue - we can just copy the `.env.example` file for ci docker image to fulfill `Joi` requirements - but if there is anything important (e.g. mongo uri) we can define it in the Dockerfile. `dotenv` will [not overwrite any existing environment variables](https://github.com/motdotla/dotenv#what-happens-to-environment-variables-that-were-already-set) so this should work.

I'll put in a PR soon.

**Comment by joshmorel** [comment]
One other thing - how do we use these? I see they are used in the raccoon library config but not sure if we have to worry about defining these in `.env` or `/config/config.js`?

```bash
RACCOON_REDIS_URL=localhost
RACCOON_REDIS_PORT=6379
```

**Comment by joshmorel** [comment]
Okay - I'm starting to see the difference between `.env.local_example` and `.env.docker_example` now. Docker uses `mongo` and `redis` instead of `localhost`. Maybe keeping both is okay or we just provide a comment in the example for those using Docker.
