### ISSUE TITLE
post.controller.find limit parameter does nothing

### ISSUE THREAD

**Issue by joshmorel** [SoftwareEngineeringDaily/software-engineering-daily-api#24]
`limit` is a parameter in the `posts.controller` `list` method but doesn't actually do anything. `post.model` expects `limitOption` instead and so the default value of 10 is always used regardless of what is provided.

I think this would be a fairly straight forward fix - but if I wanted to update the tests it gets a little more complicated (see below). So should this be done now, or, since existing front-end app functionality doesn't seem to be affected, perhaps it's better addressed along with implementation of type system - see issue #9 

For the tests - I'm looking at `post.test.js` and it seems like the idea is we're mocking the creation of data in an empty Mongo test database. However, when saving a new posts, there is no date because there is no date in the Mongoose model. As far as I can tell this is only available when loading data from wordpress - so I can't see how the `should get all posts (with limit and skip)`  test would pass with mock data (not loaded from WP). 

Anyways, I could figure this out but I'm wondering if it's worth it to be done now or just addressed along with the type system because the whole code base will be changed anyways.

**Comment by TheHollidayInn** [comment]
Thanks for posting!

If you want, feel free to add a default field to the post data which should help. You can also add a createdAt field on the post during the tests to help with the paging test.

Also, if you want to allow the limit param to take values, that is fine as well. Flow won't break any of these changes.

Is that what you are asking?

**Comment by joshmorel** [comment]
Sure! I'll take a stab.

**Comment by TheHollidayInn** [comment]
fixed in https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/pull/25
