### ISSUE TITLE
Backend API architecture

### ISSUE THREAD

**Issue by hassanfarid** [SoftwareEngineeringDaily/software-engineering-daily-api#250]
Hello,

I am starting new to this project. I was able to get it running using `docker-compose`, but honestly I have no idea where to get started from there on. I have tried to read [Backend-GettingStarted](https://softwareengineeringdaily.github.io/Backend/gettingstarted/) - not much of a guide.

Am I missing something? I started reading some code, and found where are swagger documentation. `/api/docs`.

Can we add some documentation around application architecture for good place to start? I would work on writing this, but I don't understand it myself at the moment.

**Comment by jasonify** [comment]
We've talked about adding this just a few days ago but sadly we haven't really had the time to do that yet. 

Perhaps starting by looking at the routes and tests might be a good place to get a sense of the core?

**Comment by hassanfarid** [comment]
I agree. I was thinking to start reading code, to make sense of it. Thanks for giving a direction.

**Comment by hassanfarid** [comment]
Question: How do I find database model?

I have been able to guess the use of mongodb as data source. Not so sure about redis usecase.

**Comment by hassanfarid** [comment]
I am familiar with JS, Node. Not familiar with ES6 and mocha test framework.

I started by reading,
* server/models/post.model.js
* server/routes/post.route.js
* server/controllers/post.controller.js
* server/tests/post.test.js

I tried to follow the flow for this request,
```bash
curl 'https://software-enginnering-daily-api.herokuapp.com/api/posts?page=1&type=new&createdAtBefore=2018-05-25T11:31:09.111Z' -H 'Origin: https://www.softwaredaily.com' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36' -H 'Accept: application/json, text/plain, */*' -H 'Referer: https://www.softwaredaily.com/new' -H 'Connection: keep-alive' --compressed
```

I do understand the flow a bit. The route calls `postCtrl.list` function, which prepares the query and calls `Post.list` from model.

Any help material? How can I speedup my understanding? Do you find that I am reading the code correctly?

**Comment by jasonify** [comment]
Hey, yeah I would recommend reading up on express.js since that's what we use and that's the general pattern we follow. You can find their docs and guides here: https://expressjs.com/

I would also recommend following a guide on ES6 since we use it at times and it might cause some confusion.
