### ISSUE TITLE
Contributor Pain Points & Ideas

### ISSUE THREAD

**Issue by joshmorel** [SoftwareEngineeringDaily/software-engineering-daily-api#251]
This is a **discussion** issue where we are inviting all contributors (existing and potential) to bring forth Software Daily Project pain points as well as ideas to address them. These can apply to any of the repos but I've created it here as this is the most active repo.  

Pain points are anything that creates friction in your ability to contribute to the Project. It could mostly affect part time volunteers, core maintainers, or both. After some time we can put together a plan to implement solutions to the most significant or common pain points.

**Comment by joshmorel** [comment]
### Pain point
The pain point that led me to suggest this has to do with increasing challenges in getting the back-end development environment set-up in such a way that it works like production.

Currently, the [sedaily-miner](https://github.com/SoftwareEngineeringDaily/sedaily-miner) repo is used to populate data from WordPress into the back-end database. When I started, it took a bit to figure out how to use that to get going on the back-end but it was manageable enough. But now, as the app has become more complex, this has become too confusing and manual. This makes it hard to catch up when new features are added (such as when the discuss episode forum thread was introduced) or, I imagine, harder to start for a newcomer than when I started.

### Ideas

No matter how it's done, the "miner" needs to be made an explicit dependency in the back-end. There are various ways I can imagine this being done:

1) Make it a part of the back-end repo
2) Make it an npm package which can be made a dependency

How it is built could be updated too. After so many episodes on streaming, I'm wondering if there are some good ideas from that for getting WordPress data into the back-end.

**Comment by crablar** [comment]
What if we make the production miner output a single JSON blob to a public file in an S3 bucket?

That way both production and test environments can simply read the JSON blob to have an up-to-date image of the sed site. Deploying the miner will no longer be part of the deployment process.

The miner is currently broken in prod because we redesigned the site, so @jasonify will be looking at it immediately. This is a good opportunity to improve how the miner fits into the site.

**Comment by joshmorel** [comment]
Well written @hassanfarid ! For item 1 - this was something that @andrewmarklloyd and I had been working on, however, as well as just well life/business, the main serious blocker was the non-explicit dependency of the overall architecture on `sedaily-miner` referenced above. I think if we resolve that we can really move forward with the effective dockerization of this project.

**Comment by andrewmarklloyd** [comment]
Yeah it’s been a crazy 2 weeks @joshmorel, sorry for dropping off the map. I think I’m at a place where I can work on it again. Although like you said, if the miner stuff needs working out then my vision of dockerizing the project will change.

**Comment by andrewmarklloyd** [comment]
## Pain point
Since I've been working mostly in devops, I am dependent on getting @jasonify or @crablar to configure Heroku settings, Google Domains, Slack or other tools since they require elevated permissions. 

## Ideas
I'm not sure if there are any fixes for the issues I have other than getting elevated permissions.

**Comment by jasonify** [comment]
Re: the miner.

I believe there are two biggish problems with the miner currently.

- One is that it is running on Heroku Scheduler which we've found to be a bit unreliable even when we are using the paid version (they state it is not guaranteed).

- Two, it is not relying on the RSS feed directly like most Podcast apps seem to be doing (they didn't break when our own site did). We are using this: http://softwareengineeringdaily.com/wp-json/wp/v2/posts  to mine the site, which got outdated with the Wordpress site.

**Comment by hassanfarid** [comment]
@crablar - **Was https://softwareengineeringdaily.github.io/ useful at all?**

Yes, it was helpful to some extent. The getting started guide for frontend and backend was helpful, but only worked for backend and had some dependency issues or frontend, as mentioned earlier.

How can be made more helpful? - I think we can add scripts that gets them up and running (possibly using docker), and document steps on how it worked. Like this for [example](https://github.com/alyyousuf7/docker-workshop/tree/master/lesson-8). This will help anyone get up to speed really quickly.

One thing that was missing here was, list of all components frontend, backend, utilities (miner, etc) and how they work together.

**Comment by hassanfarid** [comment]
@andrewmarklloyd , @joshmorel - For dockerized solution for the complete sedaily stack, I had following thoughts.

I see that we already have this repository, `sedaily-devops` which has been setup for only Logging, Monitoring, and Analytics. I think this repository should be one place to hold all deployment scripts across all components (frontend, backend, utilities + monitoring and analytics). All individual projects may only contain code, and sedaily-devops repository can provide multiple dockerized configurations to deploy complete stack, or part of it.

That way, we can focus on devops strategies separately for complete sedaily application and provide easy to getting started guide for all contributors.

**Comment by andrewmarklloyd** [comment]
@hassanfarid that's a good idea about consolidating all scripts to the `sedaily-devops`. Although we don't really deploy using Docker, everything is running on Heroku. So the deployment 'scripts' are really just pushing code to Heroku, and it handles the actual deployment. The Dockerized scripts i've been working on were more geared towards setting up a development environment.
