### ISSUE TITLE
Ability to Save to Listen Later From Desktop To Phone

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/software-engineering-daily-api#256]

**Comment by dasimandl** [comment]
@crablar @andrewmarklloyd Can you please clarify this issue? My interpretation is: 
 1. Save the user's last played position for a specific episode that is currently playing
      - User Story: User is listening on desktop, must leave to mobile, and if clicked they can save 
          position and pickup where left off
 2. list of episodes that will be displayed on user profile desktop/mobile marked to listen later
      - User Story: user can browse as many episodes and mark for later consumption
      - This list can also keep track of the User's last touched position of the episode?
