### ISSUE TITLE
Feature: Facebook and Google Auth

### ISSUE THREAD

**Issue by TheHollidayInn** [SoftwareEngineeringDaily/software-engineering-daily-api#3]
We need to add social auth. I'm also open to other auths as well, but Facebook and Google were requested. The requirements are:

1. 1 url, for social auth taking in the name as a param
2. A library to handle controller logic
3. The route must return the JWT. We already use JWT in the normal auth

**Comment by andrewmarklloyd** [comment]
Do you mean the API endpoint should take the name as a param? And what library did you mean?

**Comment by TheHollidayInn** [comment]
The endpoint should take the name of the social network as a param. For example `/api/v1/auth/facebook`.

Then, I would suggest using factory functions to authenticate/use `passport` if that is still up to date and maintained.

**Comment by andrewmarklloyd** [comment]
Ok that makes sense
