### ISSUE TITLE
Write guide for how to setup backend code + include mini DB dump

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/software-engineering-daily-api#30]

**Comment by TheHollidayInn** [comment]
The README has instructions.

**Comment by joshmorel** [comment]
The mini DB dump is a good idea to get people up-and-running in development.  I guess there are 2 options - using a library like: https://github.com/sharvit/mongoose-data-seed or just provide a json file with instructions to run `mongoimport`.

**Comment by TheHollidayInn** [comment]
We can just add a command to the seed.js file that inserts a bunch of documents. :D Seeding would be good.
