### ISSUE TITLE
Bookmarks Question

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/software-engineering-daily-api#320]
Is bookmarking purely client side, or could we potentially build a way to bookmark on the web frontend and users are able to listen on to their bookmarked episodes on mobile?

**Comment by sterlingrules** [comment]
For persistent bookmarking, it would not be purely client-side. We could definitely offer bookmarking on the web, as well as store a user's bookmarks and have them retrieved on mobile.

**Comment by andrewmarklloyd** [comment]
I think this is partially implemented, at least on the backend: https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/blob/master/server/controllers/bookmark.controller.js

**Comment by crablar** [comment]
@MostafaGazar @thedc89 do you know if bookmarking is synced with the backend?

**Comment by marcosschlup** [comment]
We have a ready structure (and records in the db as **favorites**) but we have nothing in the Frontend. We need to add.

In the Frontend sketch I did not find a reference for the bookmark. I think we're going to have to invent one.

**Comment by thedc89** [comment]
I think the mechanism for bookmarking is already there. When you look at the API response (provided that user is authenticated), it sends both _**upvoted**_ and _**bookmarked**_ boolean values.

I use it in iOS version to display which episode has already been upvoted/bookmarked. I think we can do it pretty much the same way on the web without any backend modifications required.

**Comment by crablar** [comment]
Thanks @thedc89 !

**Comment by MostafaGazar** [comment]
Just concurring that bookmarks are tracked on the backend. This means you have to logged in to use this feature on Android.

**Comment by sterlingrules** [comment]
Bookmarks have been added https://github.com/SoftwareEngineeringDaily/sedaily-front-end/pull/667
