### ISSUE TITLE
Add real names to account creation

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/software-engineering-daily-api#33]

**Comment by TheHollidayInn** [comment]
Maybe we should survey to ensure users want to use real names? There is probably research on the the benefits as well.

**Comment by sw-yx** [comment]
well if you're gonna make real names optional you dont really need a survey. so the real question is are you making real names mandatory?

either way im not clear what we are optimizing for here. i dont much care really, i'll just provide whatever my oauth method of chocie provides by default

**Comment by TheHollidayInn** [comment]
Jeff is thinking we don't make the optional, that is why I suggested a survey.

**Comment by crablar** [comment]
When Quora was getting off the ground, I followed the debates around their mandatory real names policy closely.

If you go back through all the online communities that have gotten popular in the last 20 years there is a clear link between complete anonymity and trolls/negativity. 

Ideally, we would have a granular anonymity system like Quora. That takes a ton of engineering horsepower to do correctly. I consider that the long-term goal.

**Comment by sw-yx** [comment]
sorry, what is granular anonymity in this context? im a quora user but this phrase doesn’t immediately make sense.  keen on how to get this community management right too. can also consider erring more restrictive first and then loosening gradually

**Comment by crablar** [comment]
Quora lets you be anonymous for specific answers, but they have policies about when they can deanonymize you (like to ban you).
