### ISSUE TITLE
Investigate Search Options

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/software-engineering-daily-api#35]
Algolia (maybe free because we are Open Source)
ElasticSearch

**Comment by bholagabbar** [comment]
Just for context, we're currently using the default search in Mongoose, visible here https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/blob/master/server/models/post.model.js#L88 . We'd want to do better than this as it isn't very accurate.

@TheHollidayInn Do we have a tagging mechanism of sorts in place? Have a look at https://www.npmjs.com/package/mongoose-text-search

**Comment by TheHollidayInn** [comment]
We have categories and tags on the Post modal, although we would need to update the mongoose schema. However, the are normalized per WP's sql structure. We would need to denormalize the text to create a text index on them.

**Comment by bholagabbar** [comment]
Erm just a little confused, how does WordPress fit into all of this?

**Comment by TheHollidayInn** [comment]
Right.. :P Sorry about that. We are writing this into some docs, but to give you context:
1. Jeff posts all podcasts on the main website: https://softwareengineeringdaily.com/ - which is a wordpress site
2. A script pulls from WP to convert the needed information into Mongo (this way we don't have to work with the WP api)
3. The above information is pulled into Post models for Mongo

**Comment by TheHollidayInn** [comment]
We are hoping to change this in the future.

**Comment by bholagabbar** [comment]
Ah now I understand. So I'd totally be down for building a new search
microservice. If you feel that's unnecessary, we could potentially modify
the schema, pull in tags, words etc and implement the search within. What
do you think?

**Comment by TheHollidayInn** [comment]
A search microservice sounds great!

**Comment by hassanfarid** [comment]
1) What fields do we have for search in post object?
2) Do we have category or tag description text as well?
3) What search relevance algorithm will best fit here?
