### ISSUE TITLE
User Profile Support

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/software-engineering-daily-api#36]

**Comment by TheHollidayInn** [comment]
@jasonify I think we have all of this correct? We just need the front end now, I believe.

**Comment by jasonify** [comment]
For the most part  yeah. There were a few modifications.  I just need to update the new properties on the user model.

WIP: https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/pull/46/files
