### ISSUE TITLE
Fix Heroku Deployment

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/software-engineering-daily-api#37]
Heroku is set up with two pipelines:
Backend: https://dashboard.heroku.com/pipelines/fede41a2-4266-4945-ad9b-6dbbc048390a
Frontend: https://dashboard.heroku.com/pipelines/05ed1ae0-571e-459b-bca2-9a3aa3562bc9

Both of these have staging environments (4 total environments)

master is deployed to all 4

Backend environments respond to Postman requests, but not frontend requests

**Comment by jasonify** [comment]
Not exactly sure what this part means: 

> Backend environments respond to Postman requests, but not frontend requests


Is that still the case?

**Comment by crablar** [comment]
All good.
