### ISSUE TITLE
Investigate Pending tests

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/software-engineering-daily-api#42]
Not sure if there should be pending tests.

**Comment by jasonify** [comment]
Now I see they are tests that are 'disabled' and have an _xit_ or _xdescribe_

**Comment by TheHollidayInn** [comment]
We should probably investigate some of those an either remove them or fix them.

**Comment by jasonify** [comment]
Agreed, I am removing dead/ unused code on the users route btw. If we ever actually use it then we can easily add it back.
