### ISSUE TITLE
Consider adding unique validator at the model level

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/software-engineering-daily-api#44]
Specifically for usernames. 

Currently done at the controller level / auth route:

https://github.com/blakehaswell/mongoose-unique-validator

**Comment by TheHollidayInn** [comment]
Could we do this with mongoose? http://mongoosejs.com/docs/validation.html.

**Comment by jasonify** [comment]
I looked briefly at that and we probably could do it by hand manually (I imagine that's what mongoose-unique-validator is doing)  . 

Though as the mongoose docs notes, their `unique` :

**The unique Option is Not a Validator**

But now I kinda don't like that mongoose-unique-validator is using the same value for that :(

**Comment by TheHollidayInn** [comment]
Hmm. I mean, we would use the username as an index. But maybe I am missing the flow.

I think this is fine if we handle at the controller level. We can have the controller search, although I would like if mongo threw an error and we caught that.
