### ISSUE TITLE
Event Log

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/software-engineering-daily-api#47]
We should make a global event log to decouple event creation from writing to the database. That will make it easier for people to build applications on top of SE Daily infrastructure.

**Comment by crablar** [comment]
![evented_sed](https://user-images.githubusercontent.com/1283090/31975748-2f29366e-b8e8-11e7-9dd7-83c82876a23c.png)

**Comment by crablar** [comment]
@andrewmarklloyd Google PubSub also an option as you pointed out

**Comment by TheHollidayInn** [comment]
Adding web hooks to the api is also an option, but I do like the separated event service. Are there some recommended kafka hosting?

**Comment by crablar** [comment]
@TheHollidayInn https://www.heroku.com/kafka

**Comment by TheHollidayInn** [comment]
Of course :P
