### ISSUE TITLE
Feature: Mark post as listened

### ISSUE THREAD

**Issue by TheHollidayInn** [SoftwareEngineeringDaily/software-engineering-daily-api#5]
We need a separate model to track user listening. This will help create recommendations for our ML algorithms, but will also help us not recommend podcast the user already listened to. Extra points if you have a good solution (probably using Redis) to quickly get what the user listened to.

**Comment by edgar971** [comment]
Here's my initial design: 

listened: 
- user_id
- post_id
- created_at
- update_at

The post will be marked as listened by calling the route via HTTP : 
/:postId/listened

To get what the user listened to you can simply do a simple mongo db query to get all items for that user id?

**Comment by TheHollidayInn** [comment]
Sounds great to me! That should meet the feature requirements for sure.

As for getting the listened to, that will work, but we will need to cache during the recommendation phase as a mongo query will be very expensive. No need to think about that now. It will overlay the query.

**Comment by edgar971** [comment]
Great, I'll start working on that!
