### ISSUE TITLE
Storing Data on Listens

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/software-engineering-daily-api#53]

**Comment by crablar** [comment]
We need to track how long each user makes it through each episode. 

This is a useful signal for how interested a given user is in a given topic. Once we have it implemented, we can do collaborative filtering in a way that doesn't require upvoting.

One way is to log the farthest timestamp that a user makes it to. Then, divide that by the length of the episode. That will give you a double representing the percentage of the episode that the user listened to.

First implementation that comes to my mind: every time a user stops an audio stream
1. log the timestamp they stop at
2. divide that timestamp by total episode length
3. save that to user database and make a new field { [ episode_id : 1312, percentage_listened : .8221] }

What is the right way to implement this?

**Comment by TheHollidayInn** [comment]
We are implementing this on the apps, but my intention was local storage.

If you just want do know for analytics purposes, we currently track play/pause events into firebase analytics. I's possible to add the userId to users if we aren't already. Firebase has a SQL query api that we can use for machine learning and exports.

If we want the data ourselves this sounds like a good use case to link up Kafka -> InfluxDB/Pig/Map Reduce

**Comment by andrewmarklloyd** [comment]
Sounds like #47 is becoming more relevant
