### ISSUE TITLE
API should not return passwords

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/software-engineering-daily-api#56]
Even if encrypted & even if returning my own password hash. 

It seems it still does return hashed passwords in certain cases.

This method did not work:

https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/issues/48

Reproduce on frontend by looking at Vuex in chrome and seeing "me.password" field

**Comment by gmemstr** [comment]
#70 fix this?
