### ISSUE TITLE
add facebook auth strategy for web

### ISSUE THREAD

**Issue by joshmorel** [SoftwareEngineeringDaily/software-engineering-daily-api#59]
Okay - I got a bit confused over this one and responded posted too quickly (web vs mobile facebook auth). But this morphs my issue into a new one - If we're going to use facebook mobile token auth should we not be implementing web based as well? I'm willing to give it a try. 

<del>I'm trying to get the API documented up-to-speed with swagger/jsdoc and am struggling with Facebook auth. It doesn't follow the typical [passport/oauth2](https://github.com/jaredhanson/passport-facebook) flow (two GET routes - one for request access, one with callback). I also don't see this in use in any of the front-ends. Can anyone provide clarity?</del>

**Comment by andrewmarklloyd** [comment]
I agree that we need to implement the client side oauth2 for the web to match both the mobile clients

**Comment by TheHollidayInn** [comment]
The reason is we don’t not use redirects via server side. Mobile and the front end js both handle redirects locally then send the OAuth token to the api for authentication
