### ISSUE TITLE
Duplicate mongo services in docker-compose.yml

### ISSUE THREAD

**Issue by andrewmarklloyd** [SoftwareEngineeringDaily/software-engineering-daily-api#61]
There are two mongodb services declared in the docker-compose.yml file: a [mongo 3.5](https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/blob/develop/docker-compose.yml#L4) and a [mongo 3.4.2](https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/blob/develop/docker-compose.yml#L43). This makes it confusing as to which container hostname to use in the [.env.docker_example](https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/blob/develop/.env.docker_example#L5).

**Comment by sgundlapalli11** [comment]
Hi, I'd like to take this on if possible. Is only the more recent version supposed to remain in the docker-compose.yml?

**Comment by andrewmarklloyd** [comment]
@TheHollidayInn which version is used in production?

**Comment by andrewmarklloyd** [comment]
I would assume the first service (the 3.5 version) would be the one to keep

**Comment by TheHollidayInn** [comment]
@sgundlapalli11 Please do! Thank you

@andrewmarklloyd I think we are on 3.4.10 actually. That is the latest stable.

**Comment by sgundlapalli11** [comment]
The PR got merged in for this. Do we close this issue now?
