### ISSUE TITLE
Rename Heroku Prod Instance

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/software-engineering-daily-api#69]
software-enginnering-daily-api -> sedaily-backend

**Comment by TheHollidayInn** [comment]
I don't think you should post these kind of things here. You should just rename the heroku instance :P. We can't fix this with a PR.

**Comment by crablar** [comment]
I want to test it after renaming it, but was in the middle of something so I wanted to write it down before I forgot.

**Comment by TheHollidayInn** [comment]
also, I'd recommend probably keeping the api name as we will have multiple backends :P
