### ISSUE TITLE
Group querying for child / reply comments

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/software-engineering-daily-api#76]
Right now we loop through parent comments and make a query for each of them to get their children. What we really should be doing is making 1 query that grabs  all the ids of the parents and then we make a second query to fetch all the children. So two queries instead of `number-of-parent-comment-queries`.

**Comment by sgundlapalli11** [comment]
I would like to take this on if possible.

 Just to understand where the issue is, is [this](https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/blob/5664f36eb976aabb76c58d03a4375b92fd5c680a/server/controllers/comment.controller.js#L107) where we are looping through the parent comments?

**Comment by jasonify** [comment]
Perfect and yeah exactly that :) .  The last two functions on the Controller.model : https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/blob/5664f36eb976aabb76c58d03a4375b92fd5c680a/server/models/comment.model.js


Note the lean() call, we modify those objects when populating the votes. 

Most of this logic could also be moved to the model like in the Post model.

**Comment by sgundlapalli11** [comment]
To approach this problem, I was going to add a method to take in all the `parentComments` and return `childrenComments`. I would make the query similar to [this](https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/blob/1af5323b6f181a40015bb2023d3aabfd7159aeae/server/models/comment.model.js#L153) to return multiple documents? 

Something I see we may have to do, is when we have all the `childrenComments`, we would then have to loop through them each one to add them to the appropriate `parentComment` which is happening [here](https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/blob/5664f36eb976aabb76c58d03a4375b92fd5c680a/server/models/comment.model.js#L202). I'm assuming that would still be preferred over sending a query for each `parentComment` though.

**Comment by jasonify** [comment]
👍  That's right, we just want to avoid the multiple queries

**Comment by sgundlapalli11** [comment]
Still working on this, just haven't been able to dedicate much time to it. Just wanted to post here to keep it updated.
