### ISSUE TITLE
Ensure Docker is still working correctly (with swagger deps)

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/software-engineering-daily-api#81]
Was sent this, will need to double check what's going on but might just need to have instructions on how to reload npm install inside the container 
<img width="1113" alt="screen shot 2017-11-09 at 3 52 14 pm" src="https://user-images.githubusercontent.com/150265/32635634-fbb1d978-c565-11e7-9380-a4abd8b791ba.png">

**Comment by andrewmarklloyd** [comment]
When new dependencies are added you have to run `docker-compose up --build, which installs the dependencies in the container per the Dockerfile. Submitted a PR to address this

**Comment by jasonify** [comment]
Awesome thanks!
