### ISSUE TITLE
Swagger Errors - schemaValidationMessages

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/software-engineering-daily-api#85]
{"schemaValidationMessages":[{"level":"error","message":"Can't read from file /api/docs/swagger.json"}]}

**Comment by joshmorel** [comment]
When exactly is this happening? Would be happy to help trouble shooting but it's not happening for me.

**Comment by jasonify** [comment]
I believe it is happening at the bottom of the /api/docs page. You might have to click to expand:

https://software-enginnering-daily-api.herokuapp.com/api/docs

Should have clarified that. Maybe this is expected?

**Comment by joshmorel** [comment]
It's not very obvious but an online swagger validator will be called in swagger-ui by default to check your swagger docs against the official spec. See: https://github.com/Orange-OpenSource/angular-swagger-ui/issues/43

It requires however a url, set in the `SwaggerUIBundle` config, that is both public and absolute. I currently set it up as relative... Either we can:

1. Programatically make it absolute
2. Don't bother, add the `validatorUrl: false` option to `SwaggerUIBundle` within "server/docs/index.html" and no error will be displayed
