### ISSUE TITLE
Add versioning to API endpoint

### ISSUE THREAD

**Issue by andrewmarklloyd** [SoftwareEngineeringDaily/software-engineering-daily-api#88]
Should we consider versioning the API. For example changing [`app.use('/api', routes);`](https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/blob/develop/config/express.js#L53) to something like `app.use('/api/v1', routes);`

**Comment by jasonify** [comment]
I've thought about this a few times considering the difference between the mobile clients + web. 

I am just not sure we are quite there yet. 
I am also not sure we would want to maintain the old versions of the API for long, unless we make the API more "public".  

How would you imagine the rest of the codebase should be handled if we do version the API? Maybe we can work it out with an example scenario?

**Comment by andrewmarklloyd** [comment]
Yeah that actually makes a lot of sense. I guess versioning the API is more for public facing API's. Versioning would require a lot of restructuring of the code base which we don't want to invest in. We should close the issue, but at least this was brought up.
