### ISSUE TITLE
Architecture: Add Flow

### ISSUE THREAD

**Issue by TheHollidayInn** [SoftwareEngineeringDaily/software-engineering-daily-api#9]
It is becoming a consensus that Javascript needs to be statically typed to prevent bugs. I'd like to add Flow to this: https://flow.org/. I'm also open to looking in to ReasonJS/ReactReason, but I think that may be front end only.

**Comment by dwgate** [comment]
Hi! If no one is working on this, I'd love to give it a shot. Is the intent to have flow on everything in the server directory? Is it required/wanted in config as well?

**Comment by TheHollidayInn** [comment]
Great! Let's start with the server directory.

**Comment by xbanks** [comment]
Would you consider using TypeScript for your static typing? I haven't personally used Flow, so you may have a great reason for using it. But I figure having some options might be useful.

**Comment by TheHollidayInn** [comment]
Sure, I'm super open as long as types are fixed :D 

Flow integrates into the bable compiler, so I like that I don't have to create separate files, etc. But, if TypeScript has a webpack flow (I'm just not super familiar). I'm open to trying. 

We have another JS repo for running "workers/queues" if you are looking for a project to test out Typescript on.

**Comment by joshmorel** [comment]
Here's a good article on why one company chose to use flow. https://www.lullabot.com/articles/flow-for-static-type-checking-javascript
